server:
  port: 9527
  servlet:
    context-path: /api

logging:
  file:
    path: logs
  level:
    cn.zhengcaiyun.idata.user.dal.dao: debug

spring:
  application:
    name: idata-portal-server
  datasource:
    hikari.poolName: HikariPool-portal-mysql
    # 待删除
    url: jdbc:mysql://mysql-5-7:30106/idata?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: root
    password: 123456
  jackson:
    default-property-inclusion: non_null
    deserialization:
      FAIL_ON_INVALID_SUBTYPE: false
      FAIL_ON_UNKNOWN_PROPERTIES: false
    date-format: yyyy-MM-dd HH:mm:ss.SSS
    time-zone: Asia/Shanghai


mybatis:
  configuration:
    map-underscore-to-camel-case: true

auth:
  jwt:
    security: mc3dLNBafcps8iAjHA6AMu3csiHjFw5EPCvoFAz85Whb9BSGBxGYnEjVkYKoeKguw9djsTTycuuoiJrgMo4oy3ECJzeuHY4QDAjhSRQZCkdL4TJ7tt

# 待删除
livy:
#  baseUrl: http://cdh4.cai-inc.com:8998
  baseUrl: http://172.29.108.194:8998
  sessionMax: 10
  dryRunPyFile: /tmp/shiyin/sqljob_dryrun.py

# 待删除
dolphin:
  baseUrl: http://ds.bigdata.cai-inc.com/dolphinscheduler
  token: ed3ed02005c030e955a76f7672747715

# 待删除
hdfs:
  nameservices: nameservice1
  nn1: 172.29.108.184:8020
  nn2: 172.29.108.185:8020
  basePath: /tmp/shiyin/
  user: hdfs

# 待删除
yarn:
  resourceManagerUri: http://bigdata-master3.cai-inc.com:8088

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

