server:
  port: 9527
  servlet:
    context-path: /api

logging:
  file:
    path: logs

spring:
  application:
    name: idata-portal-server
  datasource:
    url: jdbc:mysql://localhost:3306/idata
    username: root
    password: 12345678
